### ISSUE TITLE
关于简谱识别

### ISSUE THREAD

**Issue by william-song-shy** [Fallen-Breath/RedPiano#1]
如题，例如 `| 1 -2 |`  中的 `-` 会被识别为非法的升降号
虽然说，在短音中可以替换为 `0`，在长音中可以替换为 `1` ，但实际上还是有些不便的
不知道能不能改一下

**Comment by Fallen-Breath** [comment]
我不太了解乐理，希望可以详细描述下这种延音符的表述、转换逻辑，或者去找 redberd 沟通下

**Comment by william-song-shy** [comment]
实际上这种表达方式是为了在均分的拍子里表达一拍半，前八后十六，浮点，切分等不平衡节奏型

**Comment by william-song-shy** [comment]
从逻辑上来说，只需要把 `-` 视作前一个乐音即可

**Comment by Fallen-Breath** [comment]
> 从逻辑上来说，只需要把 `-` 视作前一个乐音即可

短音长音模式下均为如此吗？还是说只在长音时有效

**Comment by william-song-shy** [comment]
> > 从逻辑上来说，只需要把 `-` 视作前一个乐音即可
> 
> 短音长音模式下均为如此吗？还是说只在长音时有效

长音下如此，短音下直接视为 `0` 即可

**Comment by Fallen-Breath** [comment]
https://github.com/Fallen-Breath/RedPiano/actions/runs/1438271269

试下这个版本是否满足需求？

**Comment by william-song-shy** [comment]
测试了几组谱子都没有错，谢谢
